import type { Metadata } from "next";
import Image from "next/image";
import Script from "next/script";
import type { FC, ReactNode } from "react";

import { Header } from "@widgets/header";
import { UserProfile } from "@widgets/user-profile";

import { FONTS } from "@shared/config";

import "./_styles/styles.css";
import "./_styles/tailwind.css";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app"
};

type RootLayoutProps = {
	children: ReactNode;
};

const RootLayout: FC<Readonly<RootLayoutProps>> = ({ children }) => {
	return (
		<html lang="en" className={`${FONTS.Barlow.variable} h-full`}>
			<body className="relative min-h-screen min-h-dvh flex flex-col bg-(--geek-blue-11) bg-brand-violet">
				{process.env.NODE_ENV === "development" && (
					<Script
						src="https://unpkg.com/react-scan/dist/auto.global.js"
						crossOrigin="anonymous"
						strategy="beforeInteractive"
					/>
				)}
				<div className="absolute inset-0 z-30 bg-vignette"></div>
				<div className="absolute inset-0 z-10">
					<Image src="/images/shadow_1.png" alt="" className="opacity-30" fill />
				</div>
				<div className="absolute inset-0 z-20">
					<Image src="/images/shadow_2.png" alt="" className="opacity-80" fill />
				</div>
				<Header classes="relative z-50 mr-[2.5rem]">
					<UserProfile />
				</Header>
				<main className="z-50 flex-1">{children}</main>
			</body>
		</html>
	);
};

export default RootLayout;
