import type { Metadata } from "next";
import Image from "next/image";
import type { FC, ReactNode } from "react";

import { Header } from "@widgets/header";
import { UserProfile } from "@widgets/user-profile";

import { FONTS } from "@shared/config";

import "./_styles/styles.css";
import "./_styles/tailwind.css";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app"
};

type RootLayoutProps = {
	children: ReactNode;
};

const RootLayout: FC<Readonly<RootLayoutProps>> = ({ children }) => {
	return (
		<html lang="en" className={`${FONTS.Barlow.variable} h-full antialiased`}>
			<body className="relative min-h-full flex flex-col bg-(--geek-blue-11) bg-brand-gradient">
				<div className="z-30 absolute bg-vignette w-full h-full"></div>
				<div className="z-10 absolute w-full h-full">
					<Image src="/images/shadow_1.png" alt="" className="opacity-30" fill />
				</div>
				<div className="z-20 absolute w-full h-full">
					<Image src="/images/shadow_2.png" alt="" className="opacity-80" fill />
				</div>
				<Header classes="relative z-40">
					<UserProfile />
				</Header>
				<main className="relative z-50">{children}</main>
			</body>
		</html>
	);
};

export default RootLayout;
