import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import type { FC, ReactNode } from "react";

import { Header } from "@widgets/header";
import { UserProfile } from "@widgets/user-profile";

import "./_styles/styles.css";
import "./_styles/tailwind.css";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"]
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"]
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app"
};

type RootLayoutProps = {
	children: ReactNode;
};

const RootLayout: FC<Readonly<RootLayoutProps>> = ({ children }) => {
	return (
		<html lang="en" className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}>
			<body className="min-h-full flex flex-col">
				<Header>
					<UserProfile />
				</Header>
				<main>{children}</main>
			</body>
		</html>
	);
};

export default RootLayout;
