export const ICON = {
	Account: "Account",
	Google: "Google",
	Improvements: "Improvements",
	Add: "Add",
	AddCircle: "AddCircle",
	Home: "Home",
	TaskSquare: "TaskSquare",
	Projects: "Projects",
	Message: "Message",
	Settings: "Settings",
	LockedLock: "LockedLock",
	TextBold: "TextBold",
	TextItalic: "TextItalic",
	TextUnderline: "TextUnderline",
	LinkSquare: "LinkSquare",
	TextAlignLeft: "TextAlignLeft",
	TextAlignCenter: "TextAlignCenter",
	TextAlignRight: "TextAlignRight",
	TextAlignJustifyCenter: "TextAlignJustifyCenter",
	More: "More",
	Chevron: "Chevron",
	Clock: "Clock",
	Grid: "Grid",
	Filter: "Filter",
	User: "User",
	UserBold: "UserBold",
	UserSquareBold: "UserSquareBold",
	UserSquareOutline: "UserSquareOutline",
	UserOctagon: "UserOctagon",
	SendBold: "SendBold",
	Attach: "Attach",
	Smileys: "Smileys",
	SettingsOutline: "SettingsOutline",
	SettingsBold: "SettingsBold",
	CalendarAddOutline: "CalendarAddOutline",
	NotificationsOutline: "NotificationsOutline",
	NotificationsBold: "NotificationsBold",
	ArrowRightOutline: "ArrowRightOutline",
	TrashBold: "TrashBold",
	CalendarAddBold: "CalendarAddBold"
} as const;

export type IconType = (typeof ICON)[keyof typeof ICON];
