import type { Metadata } from "next";
import type { FC, ReactNode } from "react";
import { Fragment } from "react";

import { Header } from "@widgets/header";
import { UserProfile } from "@widgets/user-profile";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app"
};

type AuthLayoutProps = {
	children: ReactNode;
};

const AuthLayout: FC<Readonly<AuthLayoutProps>> = ({ children }) => {
	return (
		<Fragment>
			<Header classes="relative z-50 mr-[2.5rem]">
				<UserProfile />
			</Header>
			<main className="z-50 flex-1">{children}</main>
		</Fragment>
	);
};

export default AuthLayout;
