import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import type { FC, ReactNode } from "react";

import { ROUTES } from "@shared/config";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app"
};

type DashboardLayoutProps = {
	children: ReactNode;
};

const DashboardLayout: FC<Readonly<DashboardLayoutProps>> = ({ children }) => {
	return (
		<div className="grid grid-cols-[228px_1fr] grid-rows-[1fr] gap-x-[1.25rem] z-50 flex-1">
			<aside className="my-[0.75rem] ml-[0.75rem] bg-indigo-500" aria-labelledby="dashboard-sidebar-title">
				<h2 id="dashboard-sidebar-title" className="sr-only">
					Dashboard sidebar
				</h2>
				<button
					type="button"
					aria-label="Collapse sidebar"
					aria-expanded="true"
					aria-controls="dashboard-main-nav dashboard-projects-nav"
				>
					<span className="sr-only">Toggle sidebar</span>
					<svg
						width="7"
						height="13"
						viewBox="0 0 7 13"
						fill="none"
						xmlns="http://www.w3.org/2000/svg"
						aria-hidden="true"
						focusable="false"
					>
						<path
							d="M5.48167 11.31L1.135 6.96333C0.621667 6.45 0.621667 5.61 1.135 5.09667L5.48167 0.75"
							stroke="white"
							strokeWidth="1.5"
							strokeMiterlimit="10"
							strokeLinecap="round"
							strokeLinejoin="round"
						/>
					</svg>
				</button>
				<div>
					<figure>
						<Image src="/images/users/john_block.jpg" alt="Di Smolskii avatar" width={40} height={40} />
						<figcaption>
							<strong>Di Smolskii</strong>
							<small>Product Designer</small>
						</figcaption>
					</figure>
				</div>
				<nav id="dashboard-main-nav" aria-labelledby="dashboard-main-nav-title">
					<h3 id="dashboard-main-nav-title">Main</h3>
					<ul>
						<li>
							<Link href={ROUTES.Home}>
								<svg
									width="16"
									height="16"
									viewBox="0 0 16 16"
									fill="none"
									xmlns="http://www.w3.org/2000/svg"
									aria-hidden="true"
									focusable="false"
								>
									<path
										d="M8 12V10"
										stroke="#95ACCB"
										strokeWidth="1.5"
										strokeLinecap="round"
										strokeLinejoin="round"
									/>
									<path
										d="M6.71343 1.8812L2.09343 5.5812C1.57343 5.99454 1.2401 6.86787 1.35343 7.5212L2.2401 12.8279C2.4001 13.7745 3.30676 14.5412 4.26676 14.5412H11.7334C12.6868 14.5412 13.6001 13.7679 13.7601 12.8279L14.6468 7.5212C14.7534 6.86787 14.4201 5.99454 13.9068 5.5812L9.28676 1.88787C8.57343 1.31453 7.4201 1.31453 6.71343 1.8812Z"
										stroke="#95ACCB"
										strokeWidth="1.5"
										strokeLinecap="round"
										strokeLinejoin="round"
									/>
								</svg>
								<span>Home</span>
							</Link>
						</li>
						<li>
							<Link href={ROUTES.Tasks}>
								<svg
									width="16"
									height="16"
									viewBox="0 0 16 16"
									fill="none"
									xmlns="http://www.w3.org/2000/svg"
									aria-hidden="true"
									focusable="false"
								>
									<path
										d="M8.24609 5.91992H11.7461"
										stroke="#95ACCB"
										strokeWidth="1.5"
										strokeLinecap="round"
										strokeLinejoin="round"
									/>
									<path
										d="M4.25391 5.91992L4.75391 6.41992L6.25391 4.91992"
										stroke="#95ACCB"
										strokeWidth="1.5"
										strokeLinecap="round"
										strokeLinejoin="round"
									/>
									<path
										d="M8.24609 10.5869H11.7461"
										stroke="#95ACCB"
										strokeWidth="1.5"
										strokeLinecap="round"
										strokeLinejoin="round"
									/>
									<path
										d="M4.25391 10.5869L4.75391 11.0869L6.25391 9.58691"
										stroke="#95ACCB"
										strokeWidth="1.5"
										strokeLinecap="round"
										strokeLinejoin="round"
									/>
									<path
										d="M6.00065 14.6663H10.0007C13.334 14.6663 14.6673 13.333 14.6673 9.99967V5.99967C14.6673 2.66634 13.334 1.33301 10.0007 1.33301H6.00065C2.66732 1.33301 1.33398 2.66634 1.33398 5.99967V9.99967C1.33398 13.333 2.66732 14.6663 6.00065 14.6663Z"
										stroke="#95ACCB"
										strokeWidth="1.5"
										strokeLinecap="round"
										strokeLinejoin="round"
									/>
								</svg>
								<span>My Tasks</span>
							</Link>
						</li>
						<li>
							<Link href={ROUTES.Projects}>
								<svg
									width="16"
									height="16"
									viewBox="0 0 16 16"
									fill="none"
									xmlns="http://www.w3.org/2000/svg"
									aria-hidden="true"
									focusable="false"
								>
									<path
										d="M14.4408 6.96033L13.7874 9.747C13.2274 12.1537 12.1208 13.127 10.0408 12.927C9.70744 12.9003 9.34744 12.8403 8.96077 12.747L7.84077 12.4803C5.06077 11.8203 4.20077 10.447 4.8541 7.66033L5.50744 4.867C5.64077 4.30033 5.80077 3.807 6.00077 3.40033C6.78077 1.787 8.10744 1.35366 10.3341 1.88033L11.4474 2.14033C14.2408 2.79366 15.0941 4.17366 14.4408 6.96033Z"
										stroke="#95ACCB"
										strokeWidth="1.5"
										strokeLinecap="round"
										strokeLinejoin="round"
									/>
									<path
										d="M10.0402 12.9271C9.62689 13.2071 9.10689 13.4404 8.47356 13.6471L7.42023 13.9937C4.77356 14.8471 3.38023 14.1337 2.52023 11.4871L1.66689 8.85372C0.813561 6.20706 1.52023 4.80706 4.16689 3.95372L5.22023 3.60706C5.49356 3.52039 5.75356 3.44706 6.00023 3.40039C5.80023 3.80706 5.64023 4.30039 5.50689 4.86706L4.85356 7.66039C4.20023 10.4471 5.06023 11.8204 7.84023 12.4804L8.96023 12.7471C9.34689 12.8404 9.70689 12.9004 10.0402 12.9271Z"
										stroke="#95ACCB"
										strokeWidth="1.5"
										strokeLinecap="round"
										strokeLinejoin="round"
									/>
									<path
										d="M8.42578 5.68652L11.6591 6.50652"
										stroke="#95ACCB"
										strokeWidth="1.5"
										strokeLinecap="round"
										strokeLinejoin="round"
									/>
									<path
										d="M7.77344 8.2666L9.70677 8.75994"
										stroke="#95ACCB"
										strokeWidth="1.5"
										strokeLinecap="round"
										strokeLinejoin="round"
									/>
								</svg>
								<span>Projects</span>
							</Link>
						</li>
						<li>
							<Link href={ROUTES.Messages}>
								<svg
									width="16"
									height="16"
									viewBox="0 0 16 16"
									fill="none"
									xmlns="http://www.w3.org/2000/svg"
									aria-hidden="true"
									focusable="false"
								>
									<path
										d="M14.6673 6.66634V8.66634C14.6673 11.333 13.334 12.6663 10.6673 12.6663H10.334C10.1273 12.6663 9.92732 12.7663 9.80065 12.933L8.80065 14.2663C8.36065 14.853 7.64065 14.853 7.20065 14.2663L6.20065 12.933C6.09398 12.7863 5.84732 12.6663 5.66732 12.6663H5.33398C2.66732 12.6663 1.33398 11.9997 1.33398 8.66634V5.33301C1.33398 2.66634 2.66732 1.33301 5.33398 1.33301H9.33398"
										stroke="#95ACCB"
										strokeWidth="1.5"
										strokeMiterlimit="10"
										strokeLinecap="round"
										strokeLinejoin="round"
									/>
									<path
										d="M13.0007 4.66634C13.9211 4.66634 14.6673 3.92015 14.6673 2.99967C14.6673 2.0792 13.9211 1.33301 13.0007 1.33301C12.0802 1.33301 11.334 2.0792 11.334 2.99967C11.334 3.92015 12.0802 4.66634 13.0007 4.66634Z"
										stroke="#95ACCB"
										strokeWidth="1.5"
										strokeLinecap="round"
										strokeLinejoin="round"
									/>
									<path
										d="M10.6637 7.33333H10.6696"
										stroke="#95ACCB"
										strokeWidth="1.5"
										strokeLinecap="round"
										strokeLinejoin="round"
									/>
									<path
										d="M7.99764 7.33333H8.00363"
										stroke="#95ACCB"
										strokeWidth="1.5"
										strokeLinecap="round"
										strokeLinejoin="round"
									/>
									<path
										d="M5.32967 7.33333H5.33566"
										stroke="#95ACCB"
										strokeWidth="1.5"
										strokeLinecap="round"
										strokeLinejoin="round"
									/>
								</svg>
								<span>Messages</span>
							</Link>
						</li>
						<li>
							<Link href={ROUTES.Settings}>
								<svg
									width="16"
									height="16"
									viewBox="0 0 16 16"
									fill="none"
									xmlns="http://www.w3.org/2000/svg"
									aria-hidden="true"
									focusable="false"
								>
									<path
										d="M2 6.07292V9.91958C2 11.3329 2 11.3329 3.33333 12.2329L7 14.3529C7.55333 14.6729 8.45333 14.6729 9 14.3529L12.6667 12.2329C14 11.3329 14 11.3329 14 9.92625V6.07292C14 4.66625 14 4.66625 12.6667 3.76625L9 1.64625C8.45333 1.32625 7.55333 1.32625 7 1.64625L3.33333 3.76625C2 4.66625 2 4.66625 2 6.07292Z"
										stroke="#95ACCB"
										strokeWidth="1.5"
										strokeLinecap="round"
										strokeLinejoin="round"
									/>
									<path
										d="M8 10C9.10457 10 10 9.10457 10 8C10 6.89543 9.10457 6 8 6C6.89543 6 6 6.89543 6 8C6 9.10457 6.89543 10 8 10Z"
										stroke="#95ACCB"
										strokeWidth="1.5"
										strokeLinecap="round"
										strokeLinejoin="round"
									/>
								</svg>
								<span>Settings</span>
							</Link>
						</li>
					</ul>
				</nav>
				<nav id="dashboard-projects-nav" aria-labelledby="dashboard-projects-nav-title">
					<div>
						<h3 id="dashboard-projects-nav-title">Projects</h3>
						<button type="button" aria-label="Create new project">
							<svg
								width="16"
								height="16"
								viewBox="0 0 16 16"
								fill="none"
								xmlns="http://www.w3.org/2000/svg"
								aria-hidden="true"
								focusable="false"
							>
								<path
									d="M8.00065 1.33301C4.32732 1.33301 1.33398 4.32634 1.33398 7.99967C1.33398 11.673 4.32732 14.6663 8.00065 14.6663C11.674 14.6663 14.6673 11.673 14.6673 7.99967C14.6673 4.32634 11.674 1.33301 8.00065 1.33301ZM10.6673 8.49967H8.50065V10.6663C8.50065 10.9397 8.27398 11.1663 8.00065 11.1663C7.72732 11.1663 7.50065 10.9397 7.50065 10.6663V8.49967H5.33398C5.06065 8.49967 4.83398 8.27301 4.83398 7.99967C4.83398 7.72634 5.06065 7.49967 5.33398 7.49967H7.50065V5.33301C7.50065 5.05967 7.72732 4.83301 8.00065 4.83301C8.27398 4.83301 8.50065 5.05967 8.50065 5.33301V7.49967H10.6673C10.9407 7.49967 11.1673 7.72634 11.1673 7.99967C11.1673 8.27301 10.9407 8.49967 10.6673 8.49967Z"
									fill="#657997"
								/>
							</svg>
							<span className="sr-only">Create New Project</span>
						</button>
					</div>
					<ul>
						<li>
							<Link href={ROUTES.Project("1")}>
								<svg
									width="16"
									height="16"
									viewBox="0 0 16 16"
									fill="none"
									xmlns="http://www.w3.org/2000/svg"
									aria-hidden="true"
									focusable="false"
								>
									<path
										d="M8.99023 6.49121L11.8736 9.37457L10.3358 12.8346L6.87577 14.3724L3.99242 11.489L7.45245 9.95124L8.99023 6.49121Z"
										fill="black"
									/>
									<path
										d="M12.0078 4.51074L9.12446 1.62739L5.66443 3.16518L4.12664 6.6252L7.01 9.50856L8.54779 6.04853L12.0078 4.51074Z"
										fill="black"
									/>
								</svg>
								<span>Sleekpay App</span>
							</Link>
						</li>
						<li>
							<Link href={ROUTES.Project("2")}>
								<svg
									width="16"
									height="16"
									viewBox="0 0 16 16"
									fill="none"
									xmlns="http://www.w3.org/2000/svg"
									aria-hidden="true"
									focusable="false"
								>
									<path
										d="M12.6675 4.66634C12.6675 4.78634 12.6608 4.89967 12.6475 5.013C12.5675 5.97967 12.1408 6.853 11.4941 7.493C10.7741 8.21967 9.77413 8.66634 8.66746 8.66634H6.58079C6.24746 8.66634 5.96746 8.913 5.9208 9.23967L5.41412 12.7597C5.37412 13.0197 5.18746 13.233 4.94079 13.2997C4.88079 13.3263 4.8208 13.333 4.75413 13.333H3.45412C3.04079 13.333 2.72746 12.9663 2.79413 12.5597L4.38745 3.00635C4.54745 2.03968 5.3808 1.33301 6.3608 1.33301H9.33413C11.1741 1.33301 12.6675 2.82634 12.6675 4.66634Z"
										fill="white"
									/>
									<path
										d="M8.15039 10.417C7.98932 10.6065 7.87645 10.8406 7.83301 11.1035L7.36328 13.917H6.81543C6.97981 13.6452 7.0935 13.3385 7.1416 13.0088V13.0078L7.5166 10.417H8.15039ZM12.9883 8.46094C12.8624 8.7211 12.6957 8.95768 12.4941 9.16211C12.1224 9.52859 11.6451 9.78219 11.1123 9.875C11.7083 9.59568 12.2568 9.21339 12.7314 8.73535L12.7305 8.73438C12.8197 8.646 12.9055 8.55475 12.9883 8.46094Z"
										fill="white"
										stroke="white"
										strokeWidth="1.5"
									/>
								</svg>
								<span>PayPal App</span>
							</Link>
						</li>
						<li>
							<Link href={ROUTES.Project("3")}>
								<svg
									width="16"
									height="16"
									viewBox="0 0 16 16"
									fill="none"
									xmlns="http://www.w3.org/2000/svg"
									aria-hidden="true"
									focusable="false"
								>
									<path
										d="M8.75684 10.0527C9.28892 11.5691 9.59795 12.8718 9.76074 13.6523C9.20976 13.8237 8.62084 13.917 8.01367 13.917C6.87823 13.917 5.82267 13.6005 4.92773 13.0479C5.44669 12.3054 6.62664 10.9645 8.75684 10.0527Z"
										fill="#460455"
										stroke="#460455"
										strokeWidth="1.5"
									/>
									<path
										fillRule="evenodd"
										clipRule="evenodd"
										d="M14.5458 9.26036C14.2391 10.9004 13.3191 12.327 12.0324 13.3004C11.8924 13.407 11.6924 13.327 11.6591 13.1603C11.5191 12.4403 11.1791 10.887 10.5258 9.04035C10.4791 8.90035 10.5725 8.74701 10.7191 8.72701C12.3791 8.52701 13.8325 8.84701 14.3791 8.99367C14.4925 9.03367 14.5658 9.14702 14.5458 9.26036Z"
										fill="#460455"
									/>
									<path
										fillRule="evenodd"
										clipRule="evenodd"
										d="M14.3928 7.87978C13.7128 7.75978 11.9795 7.50643 10.2062 7.69976C10.0995 7.7131 10.0062 7.6531 9.95949 7.55309C9.93283 7.49309 9.91284 7.4331 9.88617 7.3731C9.7795 7.12644 9.66617 6.87311 9.55284 6.62644C9.49284 6.50644 9.55283 6.35976 9.67283 6.30643C11.5395 5.49976 12.5795 4.45976 12.9861 3.9931C13.0861 3.87976 13.2595 3.88644 13.3528 4.00644C14.1195 5.02644 14.5928 6.2731 14.6662 7.61977C14.6728 7.78643 14.5395 7.90644 14.3928 7.87978Z"
										fill="#460455"
									/>
									<path
										fillRule="evenodd"
										clipRule="evenodd"
										d="M12.2933 3.19318C11.9466 3.61318 10.9733 4.61316 9.12664 5.3465C9.01997 5.39316 8.8933 5.34649 8.8333 5.23983C7.97997 3.69316 7.07329 2.39316 6.65329 1.8065C6.55329 1.6665 6.63331 1.46651 6.79998 1.43984C7.18665 1.37317 7.59331 1.33984 8.00664 1.33984C9.61998 1.33984 11.1066 1.91317 12.26 2.87317C12.36 2.9465 12.3733 3.09318 12.2933 3.19318Z"
										fill="#460455"
									/>
									<path
										fillRule="evenodd"
										clipRule="evenodd"
										d="M7.34717 5.8936C4.8205 6.52693 2.58714 6.6136 1.77381 6.62694C1.62047 6.62694 1.50716 6.48027 1.54716 6.3336C2.02716 4.46694 3.30715 2.90694 4.99382 2.04694C5.09382 1.99361 5.22049 2.02693 5.28715 2.12026C5.63382 2.60026 6.57382 3.95361 7.49382 5.54694C7.56715 5.68027 7.5005 5.8536 7.34717 5.8936Z"
										fill="#460455"
									/>
									<path
										fillRule="evenodd"
										clipRule="evenodd"
										d="M8.61316 7.73308C8.67316 7.85975 8.59985 8.01308 8.46651 8.05974C5.51318 9.01308 3.74651 11.3798 3.21318 12.1931C3.12651 12.3264 2.93984 12.3331 2.83984 12.2131C1.90651 11.0664 1.33984 9.75307 1.33984 8.15974V8.03974C1.33984 7.90641 1.4465 7.79974 1.57983 7.80641C2.41983 7.83974 5.15984 7.7264 8.00651 6.9064C8.11318 6.87307 8.23316 6.92642 8.27983 7.02642C8.39316 7.25975 8.50649 7.49308 8.61316 7.73308Z"
										fill="#460455"
									/>
								</svg>
								<span>Dribble Posts</span>
							</Link>
						</li>
						<li>
							<Link href={ROUTES.Project("4")}>
								<svg
									width="16"
									height="16"
									viewBox="0 0 16 16"
									fill="none"
									xmlns="http://www.w3.org/2000/svg"
									aria-hidden="true"
									focusable="false"
								>
									<path
										d="M11.334 2.66699H4.66732C2.66732 2.66699 1.33398 4.00033 1.33398 6.00033V10.0003C1.33398 12.0003 2.66732 13.3337 4.66732 13.3337H11.334C13.334 13.3337 14.6673 12.0003 14.6673 10.0003V6.00033C14.6673 4.00033 13.334 2.66699 11.334 2.66699ZM9.26066 8.68699L7.61397 9.67367C6.94731 10.0737 6.40063 9.767 6.40063 8.987V7.007C6.40063 6.227 6.94731 5.92033 7.61397 6.32033L9.26066 7.30699C9.89399 7.69365 9.89399 8.30699 9.26066 8.68699Z"
										fill="white"
									/>
								</svg>
								<span>Youtube</span>
							</Link>
						</li>
					</ul>
				</nav>
				<section aria-labelledby="dashboard-improvements-title">
					<h3 id="dashboard-improvements-title" className="sr-only">
						Improvements
					</h3>
					<strong>Let&#39;s start!</strong>
					<p>Creating or adding new tasks couldn&#39;t be easier</p>
					<button type="button" aria-label="Open improvements">
						<svg
							width="16"
							height="16"
							viewBox="0 0 16 16"
							fill="none"
							xmlns="http://www.w3.org/2000/svg"
							aria-hidden="true"
							focusable="false"
						>
							<path
								d="M11.5262 2.7597L11.4795 5.28637C11.4729 5.63304 11.6929 6.09304 11.9729 6.2997L13.6262 7.55304C14.6862 8.35304 14.5129 9.33304 13.2462 9.73304L11.0929 10.4064C10.7329 10.5197 10.3529 10.913 10.2595 11.2797L9.7462 13.2397C9.33953 14.7864 8.3262 14.9397 7.4862 13.5797L6.31286 11.6797C6.09953 11.333 5.59286 11.073 5.19286 11.093L2.9662 11.2064C1.37286 11.2864 0.919529 10.3664 1.95953 9.15304L3.27953 7.6197C3.5262 7.33304 3.63953 6.7997 3.5262 6.4397L2.8462 4.2797C2.45286 3.01304 3.15953 2.31304 4.41953 2.72637L6.3862 3.37304C6.71953 3.4797 7.21953 3.40637 7.49953 3.1997L9.55286 1.7197C10.6662 0.92637 11.5529 1.39304 11.5262 2.7597Z"
								fill="white"
							/>
							<path
								d="M14.2935 13.6464L12.2735 11.6264C12.0802 11.4331 11.7602 11.4331 11.5669 11.6264C11.3735 11.8198 11.3735 12.1398 11.5669 12.3331L13.5869 14.3531C13.6869 14.4531 13.8135 14.4998 13.9402 14.4998C14.0669 14.4998 14.1935 14.4531 14.2935 14.3531C14.4869 14.1598 14.4869 13.8398 14.2935 13.6464Z"
								fill="white"
							/>
						</svg>
						<span>Improvements</span>
					</button>
				</section>
			</aside>
			<main className="relative my-[0.75rem] mr-[0.75rem] bg-indigo-800">
				<header>
					<h2>Dashboard</h2>
				</header>
				{children}
			</main>
		</div>
	);
};

export default DashboardLayout;
