import type { Metadata } from "next";
import type { FC, ReactNode } from "react";

import { ChangeLog } from "@widgets/change-log";
import { MainNavigation } from "@widgets/main-navigation";
import { ProjectsNavigation } from "@widgets/projects-navigation";
import { Sidebar } from "@widgets/sidebar";
import { UserInfo } from "@widgets/user-info";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app"
};

type DashboardLayoutProps = {
	children: ReactNode;
};

const DashboardLayout: FC<Readonly<DashboardLayoutProps>> = ({ children }) => {
	return (
		<div className="grid grid-cols-[228px_1fr] grid-rows-[1fr] gap-x-[1.25rem] z-50 flex-1">
			<Sidebar>
				<Sidebar.Header>
					<UserInfo />
				</Sidebar.Header>
				<Sidebar.Content>
					<MainNavigation />
					<ProjectsNavigation />
				</Sidebar.Content>
				<Sidebar.Footer>
					<ChangeLog />
				</Sidebar.Footer>
			</Sidebar>
			<main className="relative my-[0.75rem] mr-[0.75rem] bg-indigo-800">
				<header>
					<h2>Dashboard</h2>
				</header>
				{children}
			</main>
		</div>
	);
};

export default DashboardLayout;
